services:
  scrap-app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:test789@scrap-db:5432/fbscrap
    depends_on:
      - scrap-db
    restart: always

  scrap-db:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test789
      POSTGRES_DB: fbscrap
    restart: always

